server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://config-server:8888

member-service:
  url: https://drinkhere.store/api/v1/member/m